GET http://localhost:3000/api/admin/users
Content-Type: application/json
Accept: application/json
Authorization: 0d5c5e63-5fda-4bed-9820-d81d98f1cf90

###

POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "khannedy",
  "name": "Eko Kurniawan Khannedy",
  "password" : "rahasia",
  "phone" : "0865675443"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "usernameOrPhone" : "user1",
  "password" : "password123"
}


###

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 96a8bd00-a81b-4404-9f1d-4f68f5a2e998


###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 3c6c9733-f14f-4527-af65-03b816f02035

{
  "username" : "khannedy",
  "phone": "0851111111"
}


###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 57ef4cc6-00a1-45c4-8b4e-903260b0c588


###

GET http://localhost:3000/api/admin/users/get-one?username=khannedy
Content-Type: application/json
Accept: application/json
Authorization: 3c6c9733-f14f-4527-af65-03b816f02035


###

PATCH http://localhost:3000/api/admin/user/update?username=khannedy
Content-Type: application/json
Authorization: 96a8bd00-a81b-4404-9f1d-4f68f5a2e998

{
    "name": "Aom",
    "phone": "081222222",
    "role_id": 2
}