###
GET http://localhost:3000/api/admin/users
Content-Type: application/json
Accept: application/json
Authorization: 8bd51261-a252-4126-b495-452850cb92d2

###

POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "asep",
  "name": "Asep Kurniawan Khannedy",
  "password" : "rahasia",
  "phone" : "0822275443"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "usernameOrPhone" : "khannedy",
  "password" : "rahasia"
}


###

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 2fe94663-1629-49da-8b5a-2ce783de145b


###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 3c6c9733-f14f-4527-af65-03b816f02035

{
  "username" : "khannedy",
  "phone": "0851111111"
}


###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: a4bc70b5-dbd7-4e69-8c58-1cafc1c5c14a


###

GET http://localhost:3000/api/admin/users/get-one?username=khannedy
Content-Type: application/json
Accept: application/json
Authorization: 3c6c9733-f14f-4527-af65-03b816f02035


###

PATCH http://localhost:3000/api/admin/user/update?username=khannedy
Content-Type: application/json
Authorization: 96a8bd00-a81b-4404-9f1d-4f68f5a2e998

{
    "name": "Aom",
    "phone": "081222222",
    "role_id": 2
}

###
# Create UOM
POST http://localhost:3000/api/uom/create
Content-Type: application/json
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e

{
  "unit": "Kilogram",
  "isDeleted": false
}

###

# Update UOM
PUT http://localhost:3000/api/uom/update/1
Content-Type: application/json
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e

{
  "unit": "Updated Kilogram",
  "isDeleted": true
}

###

# Delete UOM
DELETE http://localhost:3000/api/uom/delete/3
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e


###
# Get One UOM
GET http://localhost:3000/api/uom/get-one/1
Content-Type: application/json
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e


###
# Get All Uom
GET http://localhost:3000/api/uom/get
Content-Type: application/json
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e


###
# Create Waste Category
POST http://localhost:3000/api/waste-category/create
Content-Type: application/json
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e

{
  "category": "Plastic",
  "isDeleted": false
}

###

# Update Waste Category
PUT http://localhost:3000/api/waste-category/update/8
Content-Type: application/json
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e

{
  "category": "Updated Plastic",
  "isDeleted": true
}

###

# Delete Waste Category
DELETE http://localhost:3000/api/waste-category/delete/8
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e


###
# Get One Waste Category
GET http://localhost:3000/api/waste-category/get-one/1
Content-Type: application/json
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e


###
# Get All Waste Category
GET http://localhost:3000/api/waste-category/get
Content-Type: application/json
Authorization: 2baa581c-cebe-48fa-9bb6-ce24dce0fc5e